### PR TITLE
Improved error pages

### PR DESCRIPTION
**Pull request by isaacfreeman**
Updated text on error pages
Added error stylesheet
Added link to home page and Breeze version info to standard error layout
Used standard error layout for IE errors

### CODE REVIEW

**Comment by isaacfreeman** [comment]
Fixes #128

**Comment by albandiguer** [comment]
Hi Isaac, can you remove the kaminari dependency please ?

**Comment by isaacfreeman** [comment]
I think you might mean nokogiri rather than kaminari.

I've removed it.

**Comment by albandiguer** [comment]
:+1: thanks

**Pull request merged**
